1.train_test_split 크기가 안 맞는 에러

원인: train_test_split(val, test_size=0.2, random_state=1, stratify = data['label'])로 해서 앞의 데이터와 다른 데이터를 넣어서

해결: data를 val로 바꿔줌


2. AttributeError: Can't get attribute 'CustomDataset' on <module '__main__' from 'run_training.py'>
저장해 둔 data loader를 불러오려다가 생긴 문제


원인: 본 파일에 CustomDataset class가 없어서

해결: from build_dataset import CustomDataset으로 클래스 불러옴

3. AttributeError: 'Namespace' object has no attribute 'epochs


원인:

해결:


data loader를 저장 https://discuss.pytorch.org/t/how-to-save-dataloader/62813/2




